INSERT INTO Customer(CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ID, PHONE_NUMBER) VALUES (1, 'raghu', 's', 'abc@bbc.com', '1234569877');
INSERT INTO Customer(CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ID, PHONE_NUMBER) VALUES (2, 'ramya', 'k', 'bbc@ccd.com', '7894561231');
INSERT INTO Customer(CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ID, PHONE_NUMBER) VALUES (3, 'naveen', 's', 'ccd@dde.com', '7894561231');
INSERT INTO Customer(CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ID, PHONE_NUMBER) VALUES (4, 'Bhargavi', 'b', 'dde@eef.com', '5874561231'); 
